### ISSUE TITLE
Can't run on macOS Sequoia

### ISSUE THREAD

**Issue by rmasoni** [MaterialFoundry/MaterialCompanion#11]
I tried running Material Companion on my M1 MacBook Pro, but it says the following:

> “Material Companion” is damaged and can’t be opened. You should move it to the Trash.

I tried both `Material.Companion-macos-arm64.dmg` and `MaterialCompanion-macos-arm64.zip` from both the Material Deck module settings page and GitHub's release page for v1.0.4.

The Stream Deck plugin was installed without issue.

I'm on macOS Sequoia 15.1.

**Comment by MaterialFoundry** [comment]
This appears to be similar to #5, which might be worth a read.

Note that many of the links are no longer working since I updated the documentation. Instructions on running and building from the source can now be found [here](https://materialfoundry.github.io/MaterialCompanion/installation/#runningbuilding-from-the-source).

**Comment by rmasoni** [comment]
Unlocking the app with `xattr -c "/Applications/Material Companion.app"` worked! Thank you!

**Comment by MaterialFoundry** [comment]
Thanks for reporting back and confirming that that worked. I've updated the documentation so it mentions it as a solution.
I will close this issue now.
