### ISSUE TITLE
macOS: “Material Companion” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by TimoLemburg** [MaterialFoundry/MaterialCompanion#5]
After downloading either the ZIP or DMG for macOS ARM and starting the Material Companion I get the message "'Material Companion' is damaged and can’t be opened. You should move it to the Bin." 

This is not the expected behaviour that macOS has in those cases that the developer is unknown.

I tried downloading with Chrome and Safari, no change.
I am using a M1 MacBook Pro with Sonoma 14.0.

**Comment by matthewbivins** [comment]
I'm also having this issue, but thinking that it might be a Sonoma thing, as I’m also running macOS14 and tried all the versions of the Companion to see if they would work. Same error, and yes, this isn't an error that we get when trying to install unknown developer apps. Thank you!

**Comment by MaterialFoundry** [comment]
I don't know why, but the macOS version keeps giving trouble. Some people with ARM processor were able to run the Intel version, but I'm guessing that @matthewbivins tried that as well. Maybe it is indeed a Sonoma thing or maybe I'm missing something. The app was built on a macOS12 virtual machine (using GitHub Actions), and unfortunately that's the latest stable virtual machine that's available.
I don't know what to do about this. I ended up using this specific method of building the app because other macOS users were mentioning that it was working for them, but this clearly isn't the case for everyone.

One thing that has, afaik, always worked, is running or building the app from the source yourselves: https://github.com/MaterialFoundry/MaterialCompanion/wiki/Installation#runningbuilding-from-the-source

**Comment by TimoLemburg** [comment]
I trues the Intel version, too and it didn’t work either. Is Python needed to actually run MaterialCompanion or just to build the app? Apple is no longer shipping macOS with Python, otherwise I would habe built it already to test it.If I find the time I‘ll build it later to try it.RegardsTimoVon meinem iPhone gesendetAm 12.11.2023 um 09:46 schrieb Material Foundry ***@***.***>:﻿
I don't know why, but the macOS version keeps giving trouble. Some people with ARM processor were able to run the Intel version, but I'm guessing that @matthewbivins tried that as well. Maybe it is indeed a Sonoma thing or maybe I'm missing something. The app was built on a macOS12 virtual machine (using GitHub Actions), and unfortunately that's the latest stable virtual machine that's available.
I don't know what to do about this. I ended up using this specific method of building the app because other macOS users were mentioning that it was working for them, but this clearly isn't the case for everyone.
One thing that has, afaik, always worked, is running or building the app from the source yourselves: https://github.com/MaterialFoundry/MaterialCompanion/wiki/Installation#runningbuilding-from-the-source

**Comment by MaterialFoundry** [comment]
Python is not needed to run the app, unless you want to use it to program the Material Plane hardware. If you want to use it for Material Plane you should install Python 3.10 because newer versions will cause problems with one of the dependencies (if you're only using the app for Material Deck you can use the latest Python 3 version).

**Comment by TimoLemburg** [comment]
After installing Xcode, node.js and Python (latest release since I am only using Material Deck) I could start the app from the Command Line, but was not able to find my StreamDecks. Foundry was able to connect, though.

After tons of tries (and searching the StreamDeck store) I finally found the streamDeckPlugin in the module description. Now it works but maybe you include in the Wiki on this page, that the streamDeckPlugin has to be installed manually :-)

**Comment by MaterialFoundry** [comment]
Happy to hear you got it to work.

The requirement to install the plugin manually can be found in the [installation instructions for Material Deck](https://github.com/MaterialFoundry/MaterialDeck/wiki/Installation). I assume that all new users look at this page, considering it's linked to in multiple places. If I start repeating the same thing at multiple places, the documentation just becomes too big, confusing, and more difficult to maintain.

**Comment by matthewbivins** [comment]
Building the app from source is no problem! I'm glad to hear that you got it to work for you, @TimoLemburg , so that's where I'm headed. Please don't worry too much about giving us a DMG, @MaterialFoundry — we know you're doing this for peanuts and the love of it, and if we're here sending Issues in Github, we're nerdy enough to install what we need via the Command Line! :) Thanks for the responses, though!

**Comment by leojackson** [comment]
This is apparently a change in behavior from macOS that marks some untrusted apps as *so* untrusted that the OS doesn't allow users to bypass it in the UI. They call such apps "broken", even though the app is fully functional. The only way I was able to get past this on my M1 MacBook Pro was by running this command in a Terminal window:

`xattr -c "/Applications/Material Companion.app"`

This manually clears the "quarantine" flag, and is akin to going to System Preferences and clicking "Allow" on an untrusted app. After running this command, the app launched with no further complaints from macOS.

*(Credit to the author of the answer to [this Apple forum post](https://discussions.apple.com/thread/253714860?sortBy=best) for clueing me in that this might be the issue.)*

For me, this behavior only happened on the Apple Silicon version of the app. I tried the Intel version, and the behavior was the expected untrusted app behavior with a bypass through System Preferences - however, the Intel app never connected to my Stream Deck or Foundry, so that's not a functional workaround.

I'm running macOS Monterey 12.6 on a 2020 M1 MacBook Pro.
